services:
  flask_app:
    container_name: flask_app
    image: p3/flask-p3-app:1.0.0
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres 
    depends_on:
      - flask_db

  flask_db:
    container_name: flask_db
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: {}
    