services:
  flask_app:
    container_name: flask_app
    image: p3/flask-p3-app:1.0.0
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://${DB_USER}:${DB_PASSWORD}@flask_db:5432/${DB_NAME}
    depends_on:
      - flask_db
    networks:
      - flask_network 

  flask_db:
    container_name: flask_db
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - flask_network



volumes:
  pgdata: {}

networks:
  flask_network: 
    